[tool.flake8]
ignore = ["D100","D103"]
exclude = [".eggs", ".git", ".tox", ".venv", ".build", "dist", "charmhelpers", "mod", "build", "lib/charms/operator_libs_linux"]
max-line-length = 99
max-complexity = 10

[tool.black]
line-length = 99
exclude = '''
(
    \.eggs
  | \.git
  | \.tox
  | \.venv
  | \.build
  | dist
  | charmhelpers
  | mod
  | build
  | lib/charms/operator_libs_linux
)/
'''

[tool.isort]
line_length = 99
profile = "black"
skip_glob = [".eggs", ".git", ".tox", ".venv", ".build", "dist", "charmhelpers", "mod", "build"]
